### ISSUE TITLE
希望扩展能支持 Firefox

### ISSUE THREAD

**Issue by Jiang10086** [liaoliao666/translate-ext#1]
如题，在 v2ex 上发现的，非常漂亮，但只支持 Chrome 系列

**Comment by liaoliao666** [comment]
好的，这周我研究下怎么上架

**Comment by Jiang10086** [comment]
感谢，已经期待起来了

发件人: ***@***.***>
发送时间: 2022年7月5日 22:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [liaoliao666/translate-ext] 希望扩展能支持 Firefox (Issue #1)


好的，这周我研究下怎么上架

―

**Comment by liaoliao666** [comment]
[Firefox 商店地址](https://addons.mozilla.org/addon/%E5%B0%8F%E5%88%92%E8%AF%8D/)
已上架，老哥可以去试用一下
