### ISSUE TITLE
从后往前选中句子的时候，翻译按钮会出现在选中区域，看不清。

### ISSUE THREAD

**Issue by scetus** [liaoliao666/translate-ext#5]
如题。

就是一个句子从后往前选择后，翻译图标会出现在选中区域（就是蓝色区域）然后就看不清了。

我觉得只要把翻译图标设置一个白色底色就可以了，这样解法比较通用，也不用在意用户是往前选择还是往后选择了。

**Comment by liaoliao666** [comment]
由于这个支持黑暗模式，使用只是单纯设为白色底色的话会很奇怪。下个版本我会考虑下怎么优化比较好😂
